name: action test
on: push
jobs:
  print_python_version:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - run: echo $PATH; python3 --version
    - run: python3 -m venv venv
    - run: ls -R venv
    - run: ls /usr/bin
